---

- block:

  - name: PostgreSQL ping dbsrv server using not default credentials and ssl
    community.general.postgresql_ping:
      login_host: "{{ database_restore_login_host }}"
      login_user: "{{ database_restore_login_user }}"
      login_password: "{{ database_restore_login_password }}"
      db: "{{ database_restore_name }}"
    register: db_ping

  # - name: Terminate source database
  #   postgresql_query:
  #     login_host: "{{ database_restore_login_host }}"
  #     login_user: "{{ database_restore_login_user }}"
  #     login_password: "{{ database_restore_login_password }}"
  #     db: "{{ database_restore_name }}"
  #     query: SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname=%s
  #     positional_args:
  #       - "{{ database_restore_name }}"

  - name: Restore to destination database
    community.postgresql.postgresql_copy:
      login_host: "{{ database_restore_login_host }}"
      login_user: "{{ database_restore_login_user }}"
      login_password: "{{ database_restore_login_password }}"
      db: "{{ database_restore_name }}"
      dst: "{{ item.value.dest_table }}"
      columns: "{{ item.value.dest_column }}"
      copy_from: "/tmp/db-table-restore--{{ item.key }}"
      program: no
      options:
        format: csv
        delimiter: "~"
        header: true
    with_dict: "{{ database_migration_map }}"
