---

- block:

  - name: Copy from backed up data
    ansible.builtin.copy:
      src: files/backup-csv
      dest: /tmp/db-table-restore--backup-csv
      force: yes

  - name: PostgreSQL ping dbsrv server using not default credentials and ssl
    community.general.postgresql_ping:
      login_host: "{{ database_restore_login_host }}"
      login_user: "{{ database_restore_login_user }}"
      login_password: "{{ database_restore_login_password }}"
      db: "{{ database_restore_name }}"
    register: db_ping

  - name: Terminate source database
    postgresql_query:
      login_host: "{{ database_restore_login_host }}"
      login_user: "{{ database_restore_login_user }}"
      login_password: "{{ database_restore_login_password }}"
      query: SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname=%s
      positional_args:
        - "{{ database_restore_name }}"

  - name: Restore to destination database
    postgresql_query:
      login_host: "{{ database_restore_login_host }}"
      login_user: "{{ database_restore_login_user }}"
      login_password: "{{ database_restore_login_password }}"
      db: "{{ database_restore_name }}"
      query: COPY {{ database_restore_table_name }}({{ database_restore_table_column_order }}) FROM %s DELIMITER '~' CSV HEADER
      positional_args:
        - /tmp/db-table-restore--backup-csv

  - name: Remove backed up data
    ansible.builtin.file:
      path: /tmp/db-table-restore--backup-csv
      state: absent
